### ISSUE TITLE
Improve catalog schema

### ISSUE THREAD

**Issue by stscijgbot-rstdms** [spacetelescope/romancal#1685]
_Issue [RCAL-1044](https://jira.stsci.edu/browse/RCAL-1044) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

The current catalog schema includes a tag for an astropy table without listing the table columns. In order to validate the table the schema should include a list of expected columns.

**Comment by braingram** [comment]
As the catalog format is approaching a "version 1" a few options for converting the current excel spreadsheet that describes the columns to a suitable ASDF schema was investigated.

Establishing an ASDF schema for the catalog will:
- provide assurance that the produced catalogs match the expected format (required columns, column datatypes)
- allow the catalog to be validated before exporting it to parquet

The desired constraints are:
- allow extra columns not defined in the schema
- allow arbitrary ordering of columns
- describe required column:
  - names
  - datatypes
  - unit

In memory the catalogs could either be astropy Table instances or structured arrays. I won't go into pros and cons of each object here but instead assume that an astropy Table will be used (as is done currently).

To construct an ASDF schema to validate column datatypes there are several options:
- add a custom validator
  - Pros: most flexible
  - Cons: schema will be ignored unless an ASDF implementation copies the python implementation of the validator
- use standard jsonschema to validate the serialized table structure
  - Pros: any ASDF implementation supporting jsonschema will be able to use the schema
  - Cons: allowing arbitrary ordering greatly complicates the schema

2 example PRs are:
- custom validator:
  - https://github.com/spacetelescope/rad/pull/566/ (to add the required schema contents)
  - https://github.com/spacetelescope/roman_datamodels/pull/478 (to implement the validator, this could be pushed upstream to asdf-astropy if a stable and general format is decided on)
- standard jsonschema:
  - https://github.com/spacetelescope/rad/pull/567
  - ideally no roman_datamodels PR would be required by due to the circular dependency of the maker_utils defining "default" objects an update is needed in: https://github.com/spacetelescope/roman_datamodels/pull/480

At this point my vote is for a custom validator. That would allow for schema contents like the following:
```yaml
    columns:
      - name: label
        required: true
        datatype: int32
```
specifying that the `label` column is required and must have an `int32` datatype. Specifying the same requirement in standard jsonschema would be the more complex:
```yaml
          columns:
            allOf:
              - not:
                  items:
                    not:
                      properties:
                        name:
                          enum: [label]
                        data:
                          properties:
                            datatype:
                              enum: [int32]
```
with the double `not` required to allow for arbitrary ordering.

Neither example above currently checks units (although either could be updated to do so). In addition to this work each approach will require:
- custom validator: decide on schema contents needed to specify the catalog structure requirements
- standard jsonschema: no specific extra work

Finally both will need to be updated when the new catalog format is decided on. Given the number of columns and that multiple schemas will be required I suggest that we implement a conversion script that generates the ASDF schema from the excel file when the final "v1.0" or whatever version we want to support is available.
